version: '3'
services:
  backend:
    image: stakingrewards/engineering-frontend-challenge:latest
    ports:
      - 8082:8081
  frontend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - backend
